var annotated_dup =
[
    [ "common", null, [
      [ "game", null, [
        [ "netbody", null, [
          [ "ClientConnect", "structcommon_1_1game_1_1netbody_1_1_client_connect.html", null ],
          [ "ClientPlayerFireBullet", "structcommon_1_1game_1_1netbody_1_1_client_player_fire_bullet.html", null ],
          [ "ClientUpdatePlayerDirection", "structcommon_1_1game_1_1netbody_1_1_client_update_player_direction.html", null ],
          [ "PingServer", "structcommon_1_1game_1_1netbody_1_1_ping_server.html", null ],
          [ "ServerAllyConnect", "structcommon_1_1game_1_1netbody_1_1_server_ally_connect.html", null ],
          [ "ServerAllyDestroy", "structcommon_1_1game_1_1netbody_1_1_server_ally_destroy.html", null ],
          [ "ServerAllyDisconnect", "structcommon_1_1game_1_1netbody_1_1_server_ally_disconnect.html", null ],
          [ "ServerAllyTakeDamage", "structcommon_1_1game_1_1netbody_1_1_server_ally_take_damage.html", null ],
          [ "ServerCreateEnemy", "structcommon_1_1game_1_1netbody_1_1_server_create_enemy.html", null ],
          [ "ServerCreatePlayerShip", "structcommon_1_1game_1_1netbody_1_1_server_create_player_ship.html", null ],
          [ "ServerDestroyBullet", "structcommon_1_1game_1_1netbody_1_1_server_destroy_bullet.html", null ],
          [ "ServerDestroyEnemy", "structcommon_1_1game_1_1netbody_1_1_server_destroy_enemy.html", null ],
          [ "ServerEnemyTakeDamage", "structcommon_1_1game_1_1netbody_1_1_server_enemy_take_damage.html", null ],
          [ "ServerFireBullet", "structcommon_1_1game_1_1netbody_1_1_server_fire_bullet.html", null ],
          [ "ServerPlayerDestroy", "structcommon_1_1game_1_1netbody_1_1_server_player_destroy.html", null ],
          [ "ServerPlayerTakeDamage", "structcommon_1_1game_1_1netbody_1_1_server_player_take_damage.html", null ],
          [ "ServerUpdateBulletPosition", "structcommon_1_1game_1_1netbody_1_1_server_update_bullet_position.html", null ],
          [ "ServerUpdateEnemyVelocity", "structcommon_1_1game_1_1netbody_1_1_server_update_enemy_velocity.html", null ],
          [ "ServerUpdateShipPosition", "structcommon_1_1game_1_1netbody_1_1_server_update_ship_position.html", null ],
          [ "ServerUpdateShipVelocity", "structcommon_1_1game_1_1netbody_1_1_server_update_ship_velocity.html", null ]
        ] ],
        [ "Entity", "classcommon_1_1game_1_1_entity.html", null ],
        [ "EntityFactory", "classcommon_1_1game_1_1_entity_factory.html", null ],
        [ "ObjectParams", "structcommon_1_1game_1_1_object_params.html", null ]
      ] ],
      [ "utils", null, [
        [ "Chrono", "classcommon_1_1utils_1_1_chrono.html", null ],
        [ "IClock", "classcommon_1_1utils_1_1_i_clock.html", null ]
      ] ]
    ] ],
    [ "ecs", null, [
      [ "components", null, [
        [ "animations", null, [
          [ "animation_s", "structecs_1_1components_1_1animations_1_1animation__s.html", "structecs_1_1components_1_1animations_1_1animation__s" ]
        ] ],
        [ "behaviour", null, [
          [ "Behaviour", "classecs_1_1components_1_1behaviour_1_1_behaviour.html", "classecs_1_1components_1_1behaviour_1_1_behaviour" ],
          [ "NetworkBehaviour", "classecs_1_1components_1_1behaviour_1_1_network_behaviour.html", "classecs_1_1components_1_1behaviour_1_1_network_behaviour" ]
        ] ],
        [ "direction", null, [
          [ "direction_s", "structecs_1_1components_1_1direction_1_1direction__s.html", null ]
        ] ],
        [ "health", null, [
          [ "health_s", "structecs_1_1components_1_1health_1_1health__s.html", null ]
        ] ],
        [ "input", null, [
          [ "Input", "structecs_1_1components_1_1input_1_1_input.html", null ],
          [ "keyState", "structecs_1_1components_1_1input_1_1key_state.html", null ],
          [ "mouseState", "structecs_1_1components_1_1input_1_1mouse_state.html", null ]
        ] ],
        [ "network", null, [
          [ "network_s", "structecs_1_1components_1_1network_1_1network__s.html", null ]
        ] ],
        [ "physics", null, [
          [ "collider_s", "structecs_1_1components_1_1physics_1_1collider__s.html", "structecs_1_1components_1_1physics_1_1collider__s" ],
          [ "rigidBody_s", "structecs_1_1components_1_1physics_1_1rigid_body__s.html", "structecs_1_1components_1_1physics_1_1rigid_body__s" ],
          [ "transform_s", "structecs_1_1components_1_1physics_1_1transform__s.html", "structecs_1_1components_1_1physics_1_1transform__s" ]
        ] ],
        [ "render", null, [
          [ "render_s", "structecs_1_1components_1_1render_1_1render__s.html", "structecs_1_1components_1_1render_1_1render__s" ]
        ] ],
        [ "sound", null, [
          [ "AudioSource", "structecs_1_1components_1_1sound_1_1_audio_source.html", null ],
          [ "MusicSource", "structecs_1_1components_1_1sound_1_1_music_source.html", null ]
        ] ],
        [ "ComponentArray", "classecs_1_1components_1_1_component_array.html", "classecs_1_1components_1_1_component_array" ],
        [ "ComponentManager", "classecs_1_1components_1_1_component_manager.html", "classecs_1_1components_1_1_component_manager" ],
        [ "Cone", "classecs_1_1components_1_1_cone.html", "classecs_1_1components_1_1_cone" ],
        [ "Cube", "classecs_1_1components_1_1_cube.html", "classecs_1_1components_1_1_cube" ],
        [ "Cylinder", "classecs_1_1components_1_1_cylinder.html", "classecs_1_1components_1_1_cylinder" ],
        [ "Hemisphere", "classecs_1_1components_1_1_hemisphere.html", "classecs_1_1components_1_1_hemisphere" ],
        [ "IComponentArray", "classecs_1_1components_1_1_i_component_array.html", null ],
        [ "IShape", "classecs_1_1components_1_1_i_shape.html", "classecs_1_1components_1_1_i_shape" ],
        [ "Knot", "classecs_1_1components_1_1_knot.html", "classecs_1_1components_1_1_knot" ],
        [ "Model3D", "classecs_1_1components_1_1_model3_d.html", "classecs_1_1components_1_1_model3_d" ],
        [ "Plane", "classecs_1_1components_1_1_plane.html", "classecs_1_1components_1_1_plane" ],
        [ "Polygon", "classecs_1_1components_1_1_polygon.html", "classecs_1_1components_1_1_polygon" ],
        [ "Skybox", "classecs_1_1components_1_1_skybox.html", "classecs_1_1components_1_1_skybox" ],
        [ "Sphere", "classecs_1_1components_1_1_sphere.html", "classecs_1_1components_1_1_sphere" ],
        [ "Torus", "classecs_1_1components_1_1_torus.html", "classecs_1_1components_1_1_torus" ]
      ] ],
      [ "event", null, [
        [ "AEvent", "classecs_1_1event_1_1_a_event.html", null ],
        [ "EventManager", "classecs_1_1event_1_1_event_manager.html", "classecs_1_1event_1_1_event_manager" ],
        [ "id", "structecs_1_1event_1_1id.html", null ],
        [ "ListenerRecord", "structecs_1_1event_1_1_listener_record.html", null ],
        [ "type", "structecs_1_1event_1_1type.html", null ]
      ] ],
      [ "system", null, [
        [ "AnimationSystem", "classecs_1_1system_1_1_animation_system.html", "classecs_1_1system_1_1_animation_system" ],
        [ "AudioSystem", "classecs_1_1system_1_1_audio_system.html", null ],
        [ "BehaviourSystem", "classecs_1_1system_1_1_behaviour_system.html", "classecs_1_1system_1_1_behaviour_system" ],
        [ "ColisionDetectionSystem", "classecs_1_1system_1_1_colision_detection_system.html", "classecs_1_1system_1_1_colision_detection_system" ],
        [ "CollisionResponse", "classecs_1_1system_1_1_collision_response.html", "classecs_1_1system_1_1_collision_response" ],
        [ "InputSystem", "classecs_1_1system_1_1_input_system.html", null ],
        [ "MusicSystem", "classecs_1_1system_1_1_music_system.html", null ],
        [ "PhysicsSystem", "classecs_1_1system_1_1_physics_system.html", "classecs_1_1system_1_1_physics_system" ],
        [ "RenderSystem", "classecs_1_1system_1_1_render_system.html", "classecs_1_1system_1_1_render_system" ],
        [ "RenderSystemDebug", "classecs_1_1system_1_1_render_system_debug.html", null ],
        [ "System", "classecs_1_1system_1_1_system.html", null ],
        [ "SystemManager", "classecs_1_1system_1_1_system_manager.html", "classecs_1_1system_1_1_system_manager" ]
      ] ],
      [ "Coordinator", "classecs_1_1_coordinator.html", "classecs_1_1_coordinator" ],
      [ "EntityManager", "classecs_1_1_entity_manager.html", "classecs_1_1_entity_manager" ],
      [ "ISingletonComponent", "classecs_1_1_i_singleton_component.html", null ],
      [ "Scene", "classecs_1_1_scene.html", null ],
      [ "SceneManager", "classecs_1_1_scene_manager.html", null ],
      [ "SingletonComponent", "classecs_1_1_singleton_component.html", null ],
      [ "SingletonComponentManager", "classecs_1_1_singleton_component_manager.html", null ]
    ] ],
    [ "engine", null, [
      [ "core", null, [
        [ "EngineCamera", "classengine_1_1core_1_1_engine_camera.html", "classengine_1_1core_1_1_engine_camera" ],
        [ "Light", "structengine_1_1core_1_1_light.html", null ],
        [ "MovableCamera", "classengine_1_1core_1_1_movable_camera.html", null ],
        [ "Window", "classengine_1_1core_1_1_window.html", "classengine_1_1core_1_1_window" ]
      ] ],
      [ "editor", null, [
        [ "ADocumentWindow", "classengine_1_1editor_1_1_a_document_window.html", "classengine_1_1editor_1_1_a_document_window" ],
        [ "AEntityProperty", "classengine_1_1editor_1_1_a_entity_property.html", "classengine_1_1editor_1_1_a_entity_property" ],
        [ "ConsoleWindow", "classengine_1_1editor_1_1_console_window.html", null ],
        [ "EntityPropertiesWindow", "classengine_1_1editor_1_1_entity_properties_window.html", null ],
        [ "GameEngineEditor", "classengine_1_1editor_1_1_game_engine_editor.html", "classengine_1_1editor_1_1_game_engine_editor" ],
        [ "IDocumentWindow", "classengine_1_1editor_1_1_i_document_window.html", null ],
        [ "IEntityProperty", "classengine_1_1editor_1_1_i_entity_property.html", null ],
        [ "LogMessage", "structengine_1_1editor_1_1_log_message.html", null ],
        [ "Main3DScene", "classengine_1_1editor_1_1_main3_d_scene.html", null ],
        [ "ModelViewerWindow", "classengine_1_1editor_1_1_model_viewer_window.html", null ],
        [ "RenderProperty", "classengine_1_1editor_1_1_render_property.html", null ],
        [ "SceneManagerBridge", "classengine_1_1editor_1_1_scene_manager_bridge.html", null ],
        [ "SceneTreeWindow", "classengine_1_1editor_1_1_scene_tree_window.html", null ],
        [ "TransformProperty", "classengine_1_1editor_1_1_transform_property.html", null ]
      ] ],
      [ "Engine", "classengine_1_1_engine.html", "classengine_1_1_engine" ]
    ] ],
    [ "ImGui", null, [
      [ "FrameTimeHistogram", "struct_im_gui_1_1_frame_time_histogram.html", null ]
    ] ],
    [ "nexo", null, [
      [ "camera", null, [
        [ "Camera", "classnexo_1_1camera_1_1_camera.html", null ],
        [ "CameraController", "classnexo_1_1camera_1_1_camera_controller.html", null ],
        [ "MockCamera", "classnexo_1_1camera_1_1_mock_camera.html", null ],
        [ "OrthographicCamera", "classnexo_1_1camera_1_1_orthographic_camera.html", null ],
        [ "OrthographicCameraController", "classnexo_1_1camera_1_1_orthographic_camera_controller.html", null ],
        [ "OrthographicCameraTest", "classnexo_1_1camera_1_1_orthographic_camera_test.html", null ],
        [ "PerspectiveCamera", "classnexo_1_1camera_1_1_perspective_camera.html", null ],
        [ "PerspectiveCameraController", "classnexo_1_1camera_1_1_perspective_camera_controller.html", null ],
        [ "PerspectiveCameraTest", "classnexo_1_1camera_1_1_perspective_camera_test.html", null ]
      ] ],
      [ "components", null, [
        [ "Cube", "structnexo_1_1components_1_1_cube.html", null ],
        [ "DirectionalLight", "structnexo_1_1components_1_1_directional_light.html", null ],
        [ "InActiveScene", "structnexo_1_1components_1_1_in_active_scene.html", null ],
        [ "Light", "structnexo_1_1components_1_1_light.html", null ],
        [ "Material", "structnexo_1_1components_1_1_material.html", null ],
        [ "Mesh", "structnexo_1_1components_1_1_mesh.html", null ],
        [ "MeshNode", "structnexo_1_1components_1_1_mesh_node.html", null ],
        [ "MockLight", "classnexo_1_1components_1_1_mock_light.html", null ],
        [ "Model", "structnexo_1_1components_1_1_model.html", null ],
        [ "PointLight", "structnexo_1_1components_1_1_point_light.html", null ],
        [ "Quad", "structnexo_1_1components_1_1_quad.html", null ],
        [ "Renderable", "structnexo_1_1components_1_1_renderable.html", null ],
        [ "Renderable2D", "structnexo_1_1components_1_1_renderable2_d.html", null ],
        [ "Renderable3D", "structnexo_1_1components_1_1_renderable3_d.html", null ],
        [ "RenderComponent", "structnexo_1_1components_1_1_render_component.html", null ],
        [ "Shape2D", "structnexo_1_1components_1_1_shape2_d.html", null ],
        [ "Shape3D", "structnexo_1_1components_1_1_shape3_d.html", null ],
        [ "SpriteComponent", "structnexo_1_1components_1_1_sprite_component.html", null ],
        [ "TransformComponent", "structnexo_1_1components_1_1_transform_component.html", null ]
      ] ],
      [ "core", null, [
        [ "FileNotFoundException", "classnexo_1_1core_1_1_file_not_found_exception.html", null ],
        [ "LoadModelException", "classnexo_1_1core_1_1_load_model_exception.html", null ]
      ] ],
      [ "ecs", null, [
        [ "AnotherComponent", "structnexo_1_1ecs_1_1_another_component.html", null ],
        [ "ComponentArray", "classnexo_1_1ecs_1_1_component_array.html", "classnexo_1_1ecs_1_1_component_array" ],
        [ "ComponentManager", "classnexo_1_1ecs_1_1_component_manager.html", "classnexo_1_1ecs_1_1_component_manager" ],
        [ "ComponentManagerTest", "classnexo_1_1ecs_1_1_component_manager_test.html", null ],
        [ "ComponentNotFound", "classnexo_1_1ecs_1_1_component_not_found.html", null ],
        [ "ComponentNotRegistered", "classnexo_1_1ecs_1_1_component_not_registered.html", null ],
        [ "Coordinator", "classnexo_1_1ecs_1_1_coordinator.html", "classnexo_1_1ecs_1_1_coordinator" ],
        [ "CoordinatorTest", "classnexo_1_1ecs_1_1_coordinator_test.html", null ],
        [ "EntityManager", "classnexo_1_1ecs_1_1_entity_manager.html", "classnexo_1_1ecs_1_1_entity_manager" ],
        [ "EntityManagerTest", "classnexo_1_1ecs_1_1_entity_manager_test.html", null ],
        [ "IComponentArray", "classnexo_1_1ecs_1_1_i_component_array.html", null ],
        [ "ISingletonComponent", "classnexo_1_1ecs_1_1_i_singleton_component.html", null ],
        [ "MockSystem", "classnexo_1_1ecs_1_1_mock_system.html", null ],
        [ "MockSystem2", "classnexo_1_1ecs_1_1_mock_system2.html", null ],
        [ "OutOfRange", "classnexo_1_1ecs_1_1_out_of_range.html", null ],
        [ "SingletonComponent", "classnexo_1_1ecs_1_1_singleton_component.html", null ],
        [ "SingletonComponentManager", "classnexo_1_1ecs_1_1_singleton_component_manager.html", null ],
        [ "SingletonComponentNotRegistered", "classnexo_1_1ecs_1_1_singleton_component_not_registered.html", null ],
        [ "System", "classnexo_1_1ecs_1_1_system.html", null ],
        [ "SystemManager", "classnexo_1_1ecs_1_1_system_manager.html", "classnexo_1_1ecs_1_1_system_manager" ],
        [ "SystemManagerTest", "classnexo_1_1ecs_1_1_system_manager_test.html", null ],
        [ "SystemNotRegistered", "classnexo_1_1ecs_1_1_system_not_registered.html", null ],
        [ "TestComponent", "structnexo_1_1ecs_1_1_test_component.html", null ],
        [ "TooManyEntities", "classnexo_1_1ecs_1_1_too_many_entities.html", null ]
      ] ],
      [ "editor", null, [
        [ "ADocumentWindow", "classnexo_1_1editor_1_1_a_document_window.html", "classnexo_1_1editor_1_1_a_document_window" ],
        [ "BackendRendererApiFatalFailure", "classnexo_1_1editor_1_1_backend_renderer_api_fatal_failure.html", null ],
        [ "BackendRendererApiFontInitFailed", "classnexo_1_1editor_1_1_backend_renderer_api_font_init_failed.html", null ],
        [ "BackendRendererApiInitFailed", "classnexo_1_1editor_1_1_backend_renderer_api_init_failed.html", null ],
        [ "BackendRendererApiNotSupported", "classnexo_1_1editor_1_1_backend_renderer_api_not_supported.html", null ],
        [ "CameraProperties", "structnexo_1_1editor_1_1_camera_properties.html", null ],
        [ "ConsoleWindow", "classnexo_1_1editor_1_1_console_window.html", null ],
        [ "Editor", "classnexo_1_1editor_1_1_editor.html", "classnexo_1_1editor_1_1_editor" ],
        [ "EntityProperties", "structnexo_1_1editor_1_1_entity_properties.html", null ],
        [ "FileNotFoundException", "classnexo_1_1editor_1_1_file_not_found_exception.html", null ],
        [ "IDocumentWindow", "classnexo_1_1editor_1_1_i_document_window.html", null ],
        [ "ImGuiBackend", "classnexo_1_1editor_1_1_im_gui_backend.html", null ],
        [ "LayerProperties", "structnexo_1_1editor_1_1_layer_properties.html", null ],
        [ "LogMessage", "structnexo_1_1editor_1_1_log_message.html", null ],
        [ "MainScene", "classnexo_1_1editor_1_1_main_scene.html", null ],
        [ "OpenGLImGuiBackend", "classnexo_1_1editor_1_1_open_g_l_im_gui_backend.html", null ],
        [ "PopupManager", "classnexo_1_1editor_1_1_popup_manager.html", null ],
        [ "SceneManagerBridge", "classnexo_1_1editor_1_1_scene_manager_bridge.html", null ],
        [ "SceneObject", "structnexo_1_1editor_1_1_scene_object.html", null ],
        [ "SceneProperties", "structnexo_1_1editor_1_1_scene_properties.html", null ],
        [ "SceneTreeWindow", "classnexo_1_1editor_1_1_scene_tree_window.html", null ],
        [ "SceneViewManager", "classnexo_1_1editor_1_1_scene_view_manager.html", null ],
        [ "TransparentStringEqual", "structnexo_1_1editor_1_1_transparent_string_equal.html", null ],
        [ "TransparentStringHash", "structnexo_1_1editor_1_1_transparent_string_hash.html", null ]
      ] ],
      [ "event", null, [
        [ "AnotherMockListener", "classnexo_1_1event_1_1_another_mock_listener.html", null ],
        [ "AnotherTestEvent", "classnexo_1_1event_1_1_another_test_event.html", null ],
        [ "BaseListener", "classnexo_1_1event_1_1_base_listener.html", null ],
        [ "Event", "classnexo_1_1event_1_1_event.html", null ],
        [ "EventAnySignal", "classnexo_1_1event_1_1_event_any_signal.html", null ],
        [ "EventKey", "classnexo_1_1event_1_1_event_key.html", null ],
        [ "EventManager", "classnexo_1_1event_1_1_event_manager.html", null ],
        [ "EventMouseClick", "classnexo_1_1event_1_1_event_mouse_click.html", null ],
        [ "EventMouseMove", "classnexo_1_1event_1_1_event_mouse_move.html", null ],
        [ "EventMouseScroll", "classnexo_1_1event_1_1_event_mouse_scroll.html", null ],
        [ "EventSignal", "classnexo_1_1event_1_1_event_signal.html", null ],
        [ "EventWindowClose", "classnexo_1_1event_1_1_event_window_close.html", null ],
        [ "EventWindowResize", "classnexo_1_1event_1_1_event_window_resize.html", null ],
        [ "IEvent", "classnexo_1_1event_1_1_i_event.html", null ],
        [ "Input", "classnexo_1_1event_1_1_input.html", null ],
        [ "InputOpenGl", "classnexo_1_1event_1_1_input_open_gl.html", null ],
        [ "Listener", "classnexo_1_1event_1_1_listener.html", null ],
        [ "Listens", "classnexo_1_1event_1_1_listens.html", null ],
        [ "MockEvent", "classnexo_1_1event_1_1_mock_event.html", null ],
        [ "MockListener", "classnexo_1_1event_1_1_mock_listener.html", null ],
        [ "MockScene", "classnexo_1_1event_1_1_mock_scene.html", null ],
        [ "MultiEventListener", "classnexo_1_1event_1_1_multi_event_listener.html", null ],
        [ "SignalHandler", "classnexo_1_1event_1_1_signal_handler.html", "classnexo_1_1event_1_1_signal_handler" ],
        [ "TestEvent", "classnexo_1_1event_1_1_test_event.html", null ]
      ] ],
      [ "layer", null, [
        [ "Layer", "classnexo_1_1layer_1_1_layer.html", null ],
        [ "LayerEventMixin", "classnexo_1_1layer_1_1_layer_event_mixin.html", null ],
        [ "LayerStack", "classnexo_1_1layer_1_1_layer_stack.html", null ],
        [ "LayerTest", "classnexo_1_1layer_1_1_layer_test.html", null ],
        [ "MockLayer", "classnexo_1_1layer_1_1_mock_layer.html", null ]
      ] ],
      [ "renderer", null, [
        [ "BufferElements", "structnexo_1_1renderer_1_1_buffer_elements.html", null ],
        [ "BufferLayout", "classnexo_1_1renderer_1_1_buffer_layout.html", null ],
        [ "BufferLayoutEmpty", "classnexo_1_1renderer_1_1_buffer_layout_empty.html", null ],
        [ "CubeVertex", "structnexo_1_1renderer_1_1_cube_vertex.html", null ],
        [ "FileNotFoundException", "classnexo_1_1renderer_1_1_file_not_found_exception.html", null ],
        [ "Framebuffer", "classnexo_1_1renderer_1_1_framebuffer.html", "classnexo_1_1renderer_1_1_framebuffer" ],
        [ "FrameBufferAttachmentsSpecifications", "structnexo_1_1renderer_1_1_frame_buffer_attachments_specifications.html", null ],
        [ "FramebufferCreationFailed", "classnexo_1_1renderer_1_1_framebuffer_creation_failed.html", null ],
        [ "FramebufferResizingFailed", "classnexo_1_1renderer_1_1_framebuffer_resizing_failed.html", null ],
        [ "FramebufferSpecs", "structnexo_1_1renderer_1_1_framebuffer_specs.html", null ],
        [ "FrameBufferTextureSpecifications", "structnexo_1_1renderer_1_1_frame_buffer_texture_specifications.html", null ],
        [ "FramebufferUnsupportedColorFormat", "classnexo_1_1renderer_1_1_framebuffer_unsupported_color_format.html", null ],
        [ "FramebufferUnsupportedDepthFormat", "classnexo_1_1renderer_1_1_framebuffer_unsupported_depth_format.html", null ],
        [ "GraphicsApiInitFailure", "classnexo_1_1renderer_1_1_graphics_api_init_failure.html", null ],
        [ "GraphicsApiNotInitialized", "classnexo_1_1renderer_1_1_graphics_api_not_initialized.html", null ],
        [ "GraphicsApiViewportResizingFailure", "classnexo_1_1renderer_1_1_graphics_api_viewport_resizing_failure.html", null ],
        [ "GraphicsApiWindowInitFailure", "classnexo_1_1renderer_1_1_graphics_api_window_init_failure.html", null ],
        [ "IndexBuffer", "classnexo_1_1renderer_1_1_index_buffer.html", "classnexo_1_1renderer_1_1_index_buffer" ],
        [ "InvalidValue", "classnexo_1_1renderer_1_1_invalid_value.html", null ],
        [ "MockIndexBuffer", "classnexo_1_1renderer_1_1_mock_index_buffer.html", null ],
        [ "MockVertexBuffer", "classnexo_1_1renderer_1_1_mock_vertex_buffer.html", null ],
        [ "OpenGlFramebuffer", "classnexo_1_1renderer_1_1_open_gl_framebuffer.html", "classnexo_1_1renderer_1_1_open_gl_framebuffer" ],
        [ "OpenGlIndexBuffer", "classnexo_1_1renderer_1_1_open_gl_index_buffer.html", "classnexo_1_1renderer_1_1_open_gl_index_buffer" ],
        [ "OpenGlRendererApi", "classnexo_1_1renderer_1_1_open_gl_renderer_api.html", "classnexo_1_1renderer_1_1_open_gl_renderer_api" ],
        [ "OpenGlShader", "classnexo_1_1renderer_1_1_open_gl_shader.html", "classnexo_1_1renderer_1_1_open_gl_shader" ],
        [ "OpenGLTest", "classnexo_1_1renderer_1_1_open_g_l_test.html", null ],
        [ "OpenGlTexture2D", "classnexo_1_1renderer_1_1_open_gl_texture2_d.html", "classnexo_1_1renderer_1_1_open_gl_texture2_d" ],
        [ "OpenGlTexture2DTest", "classnexo_1_1renderer_1_1_open_gl_texture2_d_test.html", null ],
        [ "OpenGlVertexArray", "classnexo_1_1renderer_1_1_open_gl_vertex_array.html", "classnexo_1_1renderer_1_1_open_gl_vertex_array" ],
        [ "OpenGlVertexBuffer", "classnexo_1_1renderer_1_1_open_gl_vertex_buffer.html", "classnexo_1_1renderer_1_1_open_gl_vertex_buffer" ],
        [ "OpenGlWindow", "classnexo_1_1renderer_1_1_open_gl_window.html", "classnexo_1_1renderer_1_1_open_gl_window" ],
        [ "QuadVertex", "structnexo_1_1renderer_1_1_quad_vertex.html", null ],
        [ "RenderCommand", "classnexo_1_1renderer_1_1_render_command.html", null ],
        [ "Renderer", "classnexo_1_1renderer_1_1_renderer.html", "classnexo_1_1renderer_1_1_renderer" ],
        [ "Renderer2D", "classnexo_1_1renderer_1_1_renderer2_d.html", "classnexo_1_1renderer_1_1_renderer2_d" ],
        [ "Renderer2DStorage", "structnexo_1_1renderer_1_1_renderer2_d_storage.html", null ],
        [ "Renderer2DTest", "classnexo_1_1renderer_1_1_renderer2_d_test.html", null ],
        [ "Renderer3D", "classnexo_1_1renderer_1_1_renderer3_d.html", "classnexo_1_1renderer_1_1_renderer3_d" ],
        [ "Renderer3DStats", "structnexo_1_1renderer_1_1_renderer3_d_stats.html", null ],
        [ "Renderer3DStorage", "structnexo_1_1renderer_1_1_renderer3_d_storage.html", null ],
        [ "Renderer3DTest", "classnexo_1_1renderer_1_1_renderer3_d_test.html", null ],
        [ "RendererApi", "classnexo_1_1renderer_1_1_renderer_api.html", "classnexo_1_1renderer_1_1_renderer_api" ],
        [ "RendererContext", "classnexo_1_1renderer_1_1_renderer_context.html", null ],
        [ "RendererNotInitialized", "classnexo_1_1renderer_1_1_renderer_not_initialized.html", null ],
        [ "RendererSceneLifeCycleFailure", "classnexo_1_1renderer_1_1_renderer_scene_life_cycle_failure.html", null ],
        [ "RendererStats", "structnexo_1_1renderer_1_1_renderer_stats.html", null ],
        [ "Shader", "classnexo_1_1renderer_1_1_shader.html", "classnexo_1_1renderer_1_1_shader" ],
        [ "ShaderCreationFailed", "classnexo_1_1renderer_1_1_shader_creation_failed.html", null ],
        [ "ShaderInvalidUniform", "classnexo_1_1renderer_1_1_shader_invalid_uniform.html", null ],
        [ "ShaderLibrary", "classnexo_1_1renderer_1_1_shader_library.html", null ],
        [ "ShaderTest", "classnexo_1_1renderer_1_1_shader_test.html", null ],
        [ "StbiLoadException", "classnexo_1_1renderer_1_1_stbi_load_exception.html", null ],
        [ "SubTexture2D", "classnexo_1_1renderer_1_1_sub_texture2_d.html", "classnexo_1_1renderer_1_1_sub_texture2_d" ],
        [ "Texture", "classnexo_1_1renderer_1_1_texture.html", null ],
        [ "Texture2D", "classnexo_1_1renderer_1_1_texture2_d.html", null ],
        [ "TextureInvalidSize", "classnexo_1_1renderer_1_1_texture_invalid_size.html", null ],
        [ "TextureSizeMismatch", "classnexo_1_1renderer_1_1_texture_size_mismatch.html", null ],
        [ "TextureUnsupportedFormat", "classnexo_1_1renderer_1_1_texture_unsupported_format.html", null ],
        [ "UnknownGraphicsApi", "classnexo_1_1renderer_1_1_unknown_graphics_api.html", null ],
        [ "Vertex", "structnexo_1_1renderer_1_1_vertex.html", null ],
        [ "VertexArray", "classnexo_1_1renderer_1_1_vertex_array.html", null ],
        [ "VertexBuffer", "classnexo_1_1renderer_1_1_vertex_buffer.html", "classnexo_1_1renderer_1_1_vertex_buffer" ],
        [ "Window", "classnexo_1_1renderer_1_1_window.html", null ],
        [ "WindowProperty", "structnexo_1_1renderer_1_1_window_property.html", null ]
      ] ],
      [ "scene", null, [
        [ "LightContext", "structnexo_1_1scene_1_1_light_context.html", null ],
        [ "MockCamera", "classnexo_1_1scene_1_1_mock_camera.html", null ],
        [ "MockLight", "classnexo_1_1scene_1_1_mock_light.html", null ],
        [ "Scene", "classnexo_1_1scene_1_1_scene.html", null ],
        [ "SceneContext", "structnexo_1_1scene_1_1_scene_context.html", null ],
        [ "SceneManager", "classnexo_1_1scene_1_1_scene_manager.html", null ],
        [ "SceneManagerTest", "classnexo_1_1scene_1_1_scene_manager_test.html", null ],
        [ "SceneTest", "classnexo_1_1scene_1_1_scene_test.html", null ]
      ] ],
      [ "system", null, [
        [ "OnSceneDeleted", "classnexo_1_1system_1_1_on_scene_deleted.html", null ]
      ] ],
      [ "Application", "classnexo_1_1_application.html", null ],
      [ "EntityFactory2D", "classnexo_1_1_entity_factory2_d.html", null ],
      [ "EntityFactory3D", "classnexo_1_1_entity_factory3_d.html", null ],
      [ "Exception", "classnexo_1_1_exception.html", null ],
      [ "Logger", "classnexo_1_1_logger.html", null ],
      [ "Path", "classnexo_1_1_path.html", null ],
      [ "ProfileResult", "structnexo_1_1_profile_result.html", null ],
      [ "Timer", "classnexo_1_1_timer.html", null ],
      [ "Timestep", "classnexo_1_1_timestep.html", null ]
    ] ],
    [ "rtype", null, [
      [ "net", null, [
        [ "ClientInterface", "classrtype_1_1net_1_1_client_interface.html", "classrtype_1_1net_1_1_client_interface" ],
        [ "Connection", "classrtype_1_1net_1_1_connection.html", "classrtype_1_1net_1_1_connection" ],
        [ "Message", "structrtype_1_1net_1_1_message.html", "structrtype_1_1net_1_1_message" ],
        [ "MessageHeader", "structrtype_1_1net_1_1_message_header.html", null ],
        [ "OwnedMessage", "structrtype_1_1net_1_1_owned_message.html", "structrtype_1_1net_1_1_owned_message" ],
        [ "ServerInterface", "classrtype_1_1net_1_1_server_interface.html", "classrtype_1_1net_1_1_server_interface" ],
        [ "TsQueue", "classrtype_1_1net_1_1_ts_queue.html", "classrtype_1_1net_1_1_ts_queue" ]
      ] ]
    ] ],
    [ "animation_t", "structanimation__t.html", null ],
    [ "BPLayerInterfaceImpl", "class_b_p_layer_interface_impl.html", null ],
    [ "Camera", "class_camera.html", null ],
    [ "collider_t", "structcollider__t.html", null ],
    [ "CollisionDetectionSystem", "class_collision_detection_system.html", null ],
    [ "CollisionEvent", "class_collision_event.html", null ],
    [ "ComponentArray< T >", "class_component_array_3_01_t_01_4.html", null ],
    [ "DecomposeTransformEulerTest", "class_decompose_transform_euler_test.html", null ],
    [ "Game", "class_game.html", null ],
    [ "ImGL3WProcs", "union_im_g_l3_w_procs.html", null ],
    [ "ImGui_ImplOpenGL3_Data", "struct_im_gui___impl_open_g_l3___data.html", null ],
    [ "input", "classinput.html", "classinput" ],
    [ "MovementSystem", "class_movement_system.html", null ],
    [ "MyBodyActivationListener", "class_my_body_activation_listener.html", null ],
    [ "MyContactListener", "class_my_contact_listener.html", null ],
    [ "ObjectLayerPairFilterImpl", "class_object_layer_pair_filter_impl.html", null ],
    [ "ObjectVsBroadPhaseLayerFilterImpl", "class_object_vs_broad_phase_layer_filter_impl.html", null ],
    [ "PathTestFixture", "class_path_test_fixture.html", null ],
    [ "Position", "struct_position.html", null ],
    [ "render_t", "structrender__t.html", null ],
    [ "rigidBody_t", "structrigid_body__t.html", null ],
    [ "transform_t", "structtransform__t.html", null ],
    [ "Velocity", "struct_velocity.html", null ]
];