name: Task Template
description: Use this template to create tasks for the project.
title: "[feat | fix | chore | doc]: "
labels: ["task"]
projects: ["EpitechPromo2026/1295"]

body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: A clear, concise statement of what needs to be accomplished.
      placeholder: Enter the objective of the task.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: acceptance-criteria
      description: "What are the different requirement for this task ?"
      value: |
        - [ ] 1.
        - [ ] 2.
        - [ ] 3.
        ...
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies such as other tasks, issues, or external factors that may affect the progress or scheduling of this task.
      placeholder: Enter any dependencies.

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Provide any technical details for the task.
      placeholder: |
        Environment: 
        Components: 
        Resources: 

  - type: textarea
    id: mockups-examples
    attributes:
      label: Mockups / Examples
      description: Attach any mockups, screenshots, or code examples if applicable.
      placeholder: Add any mockups or examples.

  - type: dropdown
    id: type
    attributes:
      label: type
      description: What part of the project this issue is about ?
      options:
        - Server
        - Client
        - Engine
        - Other
    validations:
      required: true
