name: Task Template
description: Use this template to create tasks for the project.
title: "[TASK_TYPE]: "
labels: ["task"]

body:
  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: Select the type of the task.
      options:
        - chore
        - feat
        - refactor
        - bug
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Title
      description: Brief title of the task, including the task type prefix.
      placeholder: Enter the task title, prefixed with the type (e.g., "feat: Add new login feature").
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: A clear, concise statement of what needs to be accomplished.
      placeholder: Enter the objective of the task.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the task.
      placeholder: Enter the detailed description of the task.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Acceptance Criteria"

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Custom Acceptance Criteria
      description: Add custom acceptance criteria as a list.
      placeholder: "- [ ] Custom criterion 1\n- [ ] Custom criterion 2"
      render: markdown

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies such as other tasks, issues, or external factors that may affect the progress or scheduling of this task.
      placeholder: Enter any dependencies.

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Provide any technical details for the task.
      placeholder: |
        Environment: 
        Components: 
        Resources: 

  - type: textarea
    id: mockups-examples
    attributes:
      label: Mockups / Examples
      description: Attach any mockups, screenshots, or code examples if applicable.
      placeholder: Add any mockups or examples.

  - type: dropdown
    id: tags
    attributes:
      label: Tags
      description: Choose tags for this issue.
      multiple: true
      options:
        - Feature
        - Bug
        - Chore
        - Documentation
        - Refactor
        - Priority: High
        - Priority: Medium
        - Priority: Low
    validations:
      required: true
