name: Task Template
description: Use this template to create tasks for the Nexo Engine project.
title: "[feat | refactor | chore | bug]: "
projects: ["NexoEngine/3"]

body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: A clear, concise statement of what needs to be accomplished.
      placeholder: Enter the objective of the task.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "What are the different requirements for this task?"
      value: |
        - [ ] 1.
        - [ ] 2.
        - [ ] 3.
        ...
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies such as other tasks, issues, or external factors that may affect the progress or scheduling of this task.
      placeholder: Enter any dependencies.

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Provide any technical details for the task.
      placeholder: |
        Environment: 
        Components: 
        Resources: 

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What part of the project is this issue about?
      options:
        - Engine
        - Editor
        - CI/CD
        - Testing
        - Documentation
        - Bug
        - Feature
        - Other
    validations:
      required: true


