//// Exceptions.hpp ///////////////////////////////////////////////////////////
//
//  zzzzz       zzz  zzzzzzzzzzzzz    zzzz      zzzz       zzzzzz  zzzzz
//  zzzzzzz     zzz  zzzz                    zzzz       zzzz           zzzz
//  zzz   zzz   zzz  zzzzzzzzzzzzz         zzzz        zzzz             zzz
//  zzz    zzz  zzz  z                  zzzz  zzzz      zzzz           zzzz
//  zzz         zzz  zzzzzzzzzzzzz    zzzz       zzz      zzzzzzz  zzzzz
//
//  Author:      Mehdy MORVAN
//  Date:        10/11/2024
//  Description: Header file for the editor exceptions
//
///////////////////////////////////////////////////////////////////////////////

#pragma once

#include "Exception.hpp"

#include <source_location>
#include <typeindex>
#include <format>

namespace nexo::editor {

    class FileNotFoundException final : public Exception {
        public:
            /**
            * @brief Constructs a FileNotFoundException.
            *
            * Initializes the exception with an error message indicating that the specified file was not found.
            * The error message is automatically formatted to include the given file path.
            *
            * @param filePath The path of the file that could not be located.
            * @param loc The source location where the exception is thrown (defaults to the current location).
            */
            explicit FileNotFoundException(const std::string &filePath,
                                    const std::source_location loc = std::source_location::current())
            	: Exception("File not found: " + filePath, loc) {}
    };

    class FileReadException final : public Exception {
        public:
            explicit FileReadException(const std::string &filePath, const std::string &message,
                                    const std::source_location loc = std::source_location::current())
            	: Exception(std::format("Error reading file {}: {}", filePath, message), loc) {}
    };

    class FileWriteException final : public Exception {
        public:
            explicit FileWriteException(const std::string &filePath, const std::string &message,
                                    const std::source_location loc = std::source_location::current())
            	: Exception(std::format("Error writing to file {}: {}", filePath, message), loc) {}
    };

    class WindowNotRegistered final : public Exception {
    	public:
     		/**
            * @brief Constructs a WindowNotRegistered exception.
            *
            * Initializes an exception indicating that the specified window type is not registered in the WindowRegistry.
            *
            * @param windowTypeIndex The type index of the unregistered window.
            * @param loc The source location where the exception is thrown (defaults to the current location).
            */
            explicit WindowNotRegistered(std::type_index windowTypeIndex, const std::source_location loc = std::source_location::current())
            	: Exception(std::format("Window not registered: {}. Make sure the window is registered in the WindowRegistry before accessing it.", windowTypeIndex.name()), loc) {}
    };

    class WindowAlreadyRegistered final : public Exception {
    	public:
     		/**
            * @brief Constructs a WindowAlreadyRegistered exception.
            *
            * Initializes an exception indicating that the specified window type with the specified name is already registered in the WindowRegistry.
            *
            * @param windowTypeIndex The type index of the unregistered window.
            * @param windowName The name of the window.
            * @param loc The source location where the exception is thrown (defaults to the current location).
            */
            explicit WindowAlreadyRegistered(std::type_index windowTypeIndex, const std::string &windowName, const std::source_location loc = std::source_location::current())
            	: Exception(std::format("Window {} already registered as: {}. Make sure the type and name is unique.", windowName, windowTypeIndex.name()), loc) {}
    };

    class BackendRendererApiNotSupported final : public Exception {
        public:
            /**
            * @brief Constructs a BackendRendererApiNotSupported exception.
            *
            * This exception is thrown when a backend render API is not supported.
            * The error message is generated by appending the given backend API name to a predefined message.
            *
            * @param backendApiName The name of the unsupported backend render API.
            * @param loc The source location where the exception is thrown, defaulting to the current location.
            */
            explicit BackendRendererApiNotSupported(const std::string &backendApiName,
                                            const std::source_location loc = std::source_location::current())
            	: Exception("Backend render API not supported: " + backendApiName, loc) {}
    };

    class BackendRendererApiInitFailed final : public Exception {
        public:
            explicit BackendRendererApiInitFailed(const std::string &backendApiName,
                                                  const std::source_location loc = std::source_location::current())
                : Exception("Backend render API init failed: " + backendApiName, loc) {}
    };

    class BackendRendererApiFontInitFailed final : public Exception {
        public:
            explicit BackendRendererApiFontInitFailed(const std::string &backendApiName,
                                                      const std::source_location loc = std::source_location::current())
                : Exception("Backend render API font init failed: " + backendApiName, loc) {}
    };

    class BackendRendererApiFatalFailure final : public Exception {
        public:
            explicit BackendRendererApiFatalFailure(const std::string &backendApiName, const std::string &message,
                                                    const std::source_location loc = std::source_location::current())
                : Exception("[" + backendApiName + " FATAL ERROR]" + message, loc) {}
    };

    class InvalidTestFileFormat final : public Exception {
        public:
            explicit InvalidTestFileFormat(const std::string &filePath, const std::string &message,
                                           const std::source_location loc = std::source_location::current())
                : Exception(std::format("Invalid test file protocol format {}: {}", filePath, message), loc) {}
    };

}
