name: Build and Package

on:
  push:
    branches:
      - feat/cicd-build
  pull_request:
    branches:
      - feat/cicd-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure vcpkg is initialized
        run: |
          if [ ! -d "./vcpkg" ]; then
            git clone https://github.com/microsoft/vcpkg.git vcpkg
          fi
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.20"

      - name: Build the project
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Copy build artifacts
        run: |
          if [ -d "./build/Release" ]; then
            cp -r ./build/Release/* ./build/
          elif [ -d "./build/Debug" ]; then
            cp -r ./build/Debug/* ./build/
          else
            echo "Build output not found" && exit 1
          fi

      - name: Copy resources
        run: |
          if [ -d "./ressources" ]; then
            cp -r ./ressources ./build/
          else
            echo "Resources directory not found" && exit 1
          fi

      - name: Package the build into a tar archive
        run: |
          tar -C $(pwd) -cf package.tar build
          if [ $? -ne 0 ]; then
            echo "Tar packaging failed" && exit 1
          fi

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: package.tar
