name: Build, test and Package

on:
  push:
    branches:
      - feat/cicd-build-refactor
  pull_request:
    branches:
      - feat/cicd-build-refactor

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        compiler: [gcc, msvc]
        include:
          - os: ubuntu-latest
            compiler: gcc
            version: 13
          - os: windows-latest
            compiler: msvc
            version: 14
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up GCC
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.compiler == 'gcc' }}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.version }}
          platform: x64

      - name: Set up Clang
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.compiler == 'clang' }}
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ matrix.version }}
          platform: x64

      - name: Set up MSVC
        if: ${{ matrix.os == 'windows-latest' && matrix.compiler == 'msvc' }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: ${{ matrix.version }}

      - name: Fetch all history for all tags and branches of vcpkg
        run: |
          cd vcpkg
          git fetch --prune --unshallow

      - name: Install latest CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ~3.30.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'vcpkg'
          buildPreset: 'vcpkg'
          testPreset: 'vcpkg'

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
        with:
          test-dir: build
          build-config: Debug
          verbose: true

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: nexo-editor-${{ matrix.compiler }}${{ matrix.version }}-${{ matrix.os }}
          path: |
            ./assets
            ./build/Debug/*
