name: Build, test and Package

on:
  push:
    branches:
      # TODO: remove this branch filter once the build is stable
      - feat/cicd-build-refactor
  pull_request:
    branches:
      - feat/cicd-build-refactor

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        compiler: [gcc, msvc]
        include:
          - os: ubuntu-latest
            compiler: gcc
            version: 13
          #- os: ubuntu-latest
          #  compiler: clang
          #  version: 13
          - os: windows-latest
            compiler: msvc
            version: 14
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up GCC
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.compiler == 'gcc' }}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.version }}
          platform: x64

      - name: Set up Clang
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.compiler == 'clang' }}
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ matrix.version }}
          platform: x64

      - name: Set up MSVC
        if: ${{ matrix.os == 'windows-latest' && matrix.compiler == 'msvc' }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: ${{ matrix.version }}

      - name: Fetch all history for all tags and branches
        run: |
          cd vcpkg
          git fetch --prune --unshallow

      - name: Install required system dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libxrandr-dev libx11-dev libxext-dev libxi-dev libgl1-mesa-dev libxinerama-dev libxcursor-dev

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.30"

      - name: Build the project
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.compiler }}
        run: |
          cmake -B build
          cmake --build build

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
        with:
          test-dir: build
          build-config: Debug
          verbose: true

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: nexo-editor-${{ matrix.compiler }}${{ matrix.version }}-${{ matrix.os }}
          path: |
            ./assets
            ./build/Debug/*
